import { Command } from "@commander-js/extra-typings";
import chalk from "chalk";
import { dim } from "@logger";
import {
  ciBuildIdOption,
  debugOption,
  disableTitleTagsOption,
  machineIdOption,
  projectOption,
  recordKeyOption,
  removeTagOption,
  reportDirOption,
  tagOption,
} from "./options";
import { uploadHandler } from "./upload";

const COMMAND_NAME = "upload";

const getExample = (name: string) => `
----------------------------------------------------
📖 Documentation: https://docs.currents.dev
🤙 Support:       support@currents.dev
----------------------------------------------------

${chalk.bold("Examples")}

Upload test results to Currents:
${dim(`${name} ${COMMAND_NAME} --key <record-key> --project-id <id> --ci-build-id <build-id>`)}

Upload test results to Currents, add tags "tagA", "tagB" to the recorded run:
${dim(
  `${name} ${COMMAND_NAME} --key <record-key> --project-id <id> --ci-build-id <build-id> --tag tagA --tag tagB`
)}

Provide a custom path to the reports directory:
${dim(
  `${name} ${COMMAND_NAME} --key <record-key> --project-id <id> --ci-build-id <build-id> --report-dir <report-dir>`
)}
`;

export const getUploadCommand = (name: string) => {
  const command = new Command()
    .name(COMMAND_NAME)
    .command(COMMAND_NAME)
    .showHelpAfterError("(add --help for additional information)")
    .allowUnknownOption()
    .description(
      `Upload test results generated by Currents reporters to https://currents.dev
${getExample(name)}`
    )
    .addOption(ciBuildIdOption)
    .addOption(recordKeyOption)
    .addOption(projectOption)
    .addOption(tagOption)
    .addOption(removeTagOption)
    .addOption(disableTitleTagsOption)
    .addOption(machineIdOption)
    .addOption(debugOption)
    .addOption(reportDirOption)
    .action((options) => uploadHandler(options));

  return command;
};
