name: unit-tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  currentsUnitTests:
    if: "!contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    name: 'Unit Tests'
    runs-on: ubuntu-22.04
    container: mcr.microsoft.com/playwright:v1.28.1-focal
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci

      - name: Run Tests
        working-directory: ./packages/cmd
        run: |
          npm run test
